//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpbl3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public int IDDV { get; set; }
        public string TenDichVu { get; set; }
        public Nullable<long> GiaTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string DonVi { get; set; }
        public string GhiChu { get; set; }
    }
}
