//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpbl3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int IDHoaDon { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> ThoiGianGD { get; set; }
        public Nullable<long> TongTien { get; set; }
        public Nullable<long> GiaPhong { get; set; }
        public Nullable<long> GiaDichVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
