//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webpbl3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int IDPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> KhongGian { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> IDLoaiPhong { get; set; }
        public Nullable<int> IDViTri { get; set; }
        public Nullable<long> GiaKM { get; set; }
        public Nullable<int> IDHinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual HinhAnh HinhAnh { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual ViTri ViTri { get; set; }
    }
}
